/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Single source of truth for all data model definitions across Go and NodeJS backends
 */
export interface AIUsageDashboardDataModels {
  [k: string]: unknown;
}
/**
 * Token usage metrics for one assistant turn
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "Usage".
 */
export interface Usage {
  /**
   * Number of input tokens consumed
   */
  input_tokens: number;
  /**
   * Number of output tokens generated
   */
  output_tokens: number;
  /**
   * Number of input tokens read from cache
   */
  cache_read_input_tokens?: number;
  /**
   * Number of input tokens used to create cache
   */
  cache_creation_input_tokens?: number;
  [k: string]: unknown;
}
/**
 * One tool invocation with its key input
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "ToolDetail".
 */
export interface ToolDetail {
  /**
   * Name of the tool invoked
   */
  tool: string;
  /**
   * Key input parameter or summary for the tool call
   */
  input?: string;
  [k: string]: unknown;
}
/**
 * A matched user→assistant turn pair representing one complete exchange
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "ConversationPair".
 */
export interface ConversationPair {
  /**
   * Unique identifier for the session containing this conversation
   */
  session_id: string;
  /**
   * Directory path of the project being worked on
   */
  project_dir: string;
  /**
   * Git branch active during this conversation
   */
  git_branch?: string;
  /**
   * Model name used (e.g., 'claude-3-5-sonnet-20241022')
   */
  model: string;
  /**
   * The user's message/prompt text
   */
  user_text: string;
  /**
   * The assistant's response text
   */
  assist_text: string;
  /**
   * List of tool names invoked in this turn
   */
  tool_calls?: string[];
  /**
   * Ordered list of tool invocations with their inputs
   */
  tool_details?: ToolDetail[];
  usage?: Usage1;
  /**
   * Duration of the turn in milliseconds
   */
  duration_ms?: number;
  /**
   * ISO 8601 timestamp when this exchange occurred
   */
  timestamp: string;
  /**
   * Percentage of context window used in this turn (0-100)
   */
  context_pct?: number;
  /**
   * Estimated cost in USD for this exchange
   */
  cost: number;
  /**
   * Quality rating of the user's prompt (1-10 scale)
   */
  prompt_score?: number;
  /**
   * Improvement suggestions for the user's prompt
   */
  prompt_tips?: string[];
  [k: string]: unknown;
}
/**
 * Token usage metrics for this exchange
 */
export interface Usage1 {
  /**
   * Number of input tokens consumed
   */
  input_tokens: number;
  /**
   * Number of output tokens generated
   */
  output_tokens: number;
  /**
   * Number of input tokens read from cache
   */
  cache_read_input_tokens?: number;
  /**
   * Number of input tokens used to create cache
   */
  cache_creation_input_tokens?: number;
  [k: string]: unknown;
}
/**
 * Aggregated token and cost statistics for a single day
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "DailyStats".
 */
export interface DailyStats {
  /**
   * Date in YYYY-MM-DD format
   */
  date: string;
  /**
   * Total input tokens consumed on this date
   */
  input_tokens: number;
  /**
   * Total output tokens generated on this date
   */
  output_tokens: number;
  /**
   * Total cache read tokens on this date
   */
  cache_read?: number;
  /**
   * Total cache creation tokens on this date
   */
  cache_creation?: number;
  /**
   * Number of sessions on this date
   */
  sessions: number;
  /**
   * Estimated total cost in USD for this date
   */
  est_cost_usd: number;
  [k: string]: unknown;
}
/**
 * Represents a parsed Claude Code session with all metadata and usage
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "Session".
 */
export interface Session {
  /**
   * Unique session identifier
   */
  id: string;
  /**
   * Full path to the session file
   */
  file_path?: string;
  /**
   * Root directory of the project being worked on
   */
  project_dir: string;
  /**
   * Git branch name active during the session
   */
  git_branch?: string;
  /**
   * Model name used throughout the session
   */
  model: string;
  /**
   * ISO 8601 timestamp when session started
   */
  start_time: string;
  /**
   * ISO 8601 timestamp when session ended
   */
  end_time: string;
  /**
   * Number of user messages in the session
   */
  user_turns: number;
  /**
   * Number of assistant messages in the session
   */
  assist_turns: number;
  total_usage: Usage2;
  /**
   * Map of tool names to invocation counts
   */
  tool_counts?: {
    [k: string]: number;
  };
  /**
   * Map of tool names to up to 5 sample input examples
   */
  tool_samples?: {
    [k: string]: string[];
  };
  /**
   * The very first user prompt in the session
   */
  first_prompt?: string;
  /**
   * Source IDE or editor where the session originated
   */
  source: "claude-code" | "github-copilot" | "opencode" | "windsurf";
  /**
   * Maximum duration of any single turn in milliseconds
   */
  max_turn_duration_ms?: number;
  /**
   * Average duration across all turns in milliseconds
   */
  avg_turn_duration_ms?: number;
  [k: string]: unknown;
}
/**
 * Aggregated token usage for the entire session
 */
export interface Usage2 {
  /**
   * Number of input tokens consumed
   */
  input_tokens: number;
  /**
   * Number of output tokens generated
   */
  output_tokens: number;
  /**
   * Number of input tokens read from cache
   */
  cache_read_input_tokens?: number;
  /**
   * Number of input tokens used to create cache
   */
  cache_creation_input_tokens?: number;
  [k: string]: unknown;
}
/**
 * Aggregated token usage and cost statistics for a single model
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "ModelStats".
 */
export interface ModelStats {
  /**
   * Model name (e.g., 'claude-3-5-sonnet-20241022')
   */
  model: string;
  /**
   * Total input tokens consumed with this model
   */
  input_tokens: number;
  /**
   * Total output tokens generated with this model
   */
  output_tokens: number;
  /**
   * Total cache read input tokens for this model
   */
  cache_read_input_tokens?: number;
  /**
   * Total cache creation input tokens for this model
   */
  cache_creation_input_tokens?: number;
  /**
   * Estimated total cost in USD for this model
   */
  est_cost_usd: number;
  [k: string]: unknown;
}
/**
 * Summary of usage for a single tool across all sessions
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "ToolUsage".
 */
export interface ToolUsage {
  /**
   * Name of the tool (e.g., 'Bash', 'Read', 'Edit')
   */
  name: string;
  /**
   * Total number of times this tool was invoked
   */
  count: number;
  /**
   * Example input or usage pattern for this tool
   */
  example?: string;
  [k: string]: unknown;
}
/**
 * One task from the task management system
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "TaskItem".
 */
export interface TaskItem {
  /**
   * Unique task identifier
   */
  id: string;
  /**
   * Brief task title in imperative form
   */
  subject: string;
  /**
   * Detailed description of what needs to be done
   */
  description: string;
  /**
   * Present continuous form shown when task is in progress
   */
  active_form?: string;
  /**
   * Current status of the task
   */
  status: "pending" | "in_progress" | "completed";
  /**
   * IDs of tasks that cannot start until this task is completed
   */
  blocks?: string[];
  /**
   * IDs of tasks that must be completed before this task can start
   */
  blocked_by?: string[];
  /**
   * Session ID where this task was created
   */
  session_id?: string;
  /**
   * Date of the session in YYYY-MM-DD format
   */
  session_date?: string;
  /**
   * Project directory associated with this task
   */
  project_dir?: string;
  [k: string]: unknown;
}
/**
 * One content block from a message (text, thinking, or tool_use)
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "RawContent".
 */
export interface RawContent {
  /**
   * Type of content block
   */
  type: "text" | "thinking" | "tool_use";
  /**
   * Text content when type is 'text'
   */
  text?: string;
  /**
   * Thinking content when type is 'thinking'
   */
  thinking?: string;
  /**
   * Tool name when type is 'tool_use'
   */
  name?: string;
  /**
   * Input parameters for the tool when type is 'tool_use' (can be any JSON value)
   */
  input?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * Message payload from a session entry
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "RawMessage".
 */
export interface RawMessage {
  /**
   * Role of the message sender
   */
  role: "user" | "assistant";
  /**
   * Model name that generated this message (assistant only)
   */
  model?: string;
  /**
   * Message content - can be array of content blocks or plain string
   */
  content: {
    [k: string]: unknown;
  };
  usage?: Usage3;
  [k: string]: unknown;
}
/**
 * Token usage for this message
 */
export interface Usage3 {
  /**
   * Number of input tokens consumed
   */
  input_tokens: number;
  /**
   * Number of output tokens generated
   */
  output_tokens: number;
  /**
   * Number of input tokens read from cache
   */
  cache_read_input_tokens?: number;
  /**
   * Number of input tokens used to create cache
   */
  cache_creation_input_tokens?: number;
  [k: string]: unknown;
}
/**
 * One line from a Claude Code JSONL session file
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "RawEntry".
 */
export interface RawEntry {
  /**
   * Entry type (e.g., 'message', 'tool', 'event')
   */
  type: string;
  /**
   * Entry subtype for additional categorization
   */
  subtype?: string;
  /**
   * Unique identifier for this entry
   */
  uuid: string;
  /**
   * ISO 8601 timestamp of this entry
   */
  timestamp: string;
  message?: RawMessage1;
  /**
   * Duration of the operation in milliseconds
   */
  duration_ms?: number;
  /**
   * Git branch name at the time of this entry
   */
  git_branch?: string;
  [k: string]: unknown;
}
/**
 * Message payload if this is a message entry
 */
export interface RawMessage1 {
  /**
   * Role of the message sender
   */
  role: "user" | "assistant";
  /**
   * Model name that generated this message (assistant only)
   */
  model?: string;
  /**
   * Message content - can be array of content blocks or plain string
   */
  content: {
    [k: string]: unknown;
  };
  usage?: Usage3;
  [k: string]: unknown;
}
/**
 * One scored dimension in the prompt quality breakdown
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "InsightDimension".
 */
export interface InsightDimension {
  /**
   * Display name of the dimension
   */
  label: string;
  /**
   * Score for this dimension (0-100)
   */
  score: number;
  /**
   * Performance tier (e.g., 'Bronze', 'Silver', 'Gold')
   */
  tier: string;
  /**
   * Current value or status string
   */
  value?: string;
  /**
   * Plain English explanation of this dimension
   */
  description?: string;
  [k: string]: unknown;
}
/**
 * One actionable finding or recommendation
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "Insight".
 */
export interface Insight {
  /**
   * Type of insight
   */
  type: "warning" | "info" | "success" | "error";
  /**
   * Brief title of the insight
   */
  title: string;
  /**
   * Detailed explanation
   */
  text: string;
  /**
   * Expected impact of addressing this insight
   */
  impact?: string;
  [k: string]: unknown;
}
/**
 * Real prompt from user's conversations with before/after comparison
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "PromptExample".
 */
export interface PromptExample {
  /**
   * Actual prompt from the user's conversations
   */
  bad: string;
  /**
   * Rewritten version showing how to improve
   */
  good: string;
  /**
   * Short explanation of the improvement
   */
  why: string;
  [k: string]: unknown;
}
/**
 * Gap between current tier and next tier for one dimension
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "TierGoal".
 */
export interface TierGoal {
  /**
   * Name of the dimension
   */
  dimension: string;
  /**
   * Current value of this dimension
   */
  current_value: string;
  /**
   * Target value needed for next tier
   */
  target_value: string;
  /**
   * Gap between current and target
   */
  delta?: string;
  /**
   * Current tier (e.g., 'Bronze')
   */
  current_tier: string;
  /**
   * Next tier to achieve (e.g., 'Silver')
   */
  next_tier: string;
  /**
   * Whether target is already met
   */
  met: boolean;
  /**
   * Whether this dimension is holding back overall tier
   */
  is_weakest?: boolean;
  /**
   * Real prompts showing improvement areas
   */
  examples?: PromptExample[];
  [k: string]: unknown;
}
/**
 * One actionable prompt improvement pattern from Claude Haiku analysis
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "HaikuImprovement".
 */
export interface HaikuImprovement {
  /**
   * Pattern or issue identified
   */
  pattern: string;
  /**
   * Example of how to fix this pattern
   */
  example_fix: string;
  /**
   * Expected impact of applying this improvement
   */
  impact: "high" | "medium";
  [k: string]: unknown;
}
/**
 * Before/after rewrite of the user's weakest prompt
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "HaikuRewrite".
 */
export interface HaikuRewrite {
  /**
   * Original user prompt
   */
  original: string;
  /**
   * Rewritten version of the prompt
   */
  improved: string;
  /**
   * Explanation of why the rewrite is better
   */
  why: string;
  [k: string]: unknown;
}
/**
 * Structured response from Claude Haiku analysis
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "HaikuAnalysis".
 */
export interface HaikuAnalysis {
  /**
   * Explanation of the user's current tier
   */
  tier_justification: string;
  /**
   * Top improvement patterns identified
   */
  top_improvements: HaikuImprovement[];
  /**
   * Strengths in the user's prompting
   */
  strengths: string[];
  rewrite?: HaikuRewrite1;
  /**
   * Additional insights and findings
   */
  insights?: Insight[];
  /**
   * ISO 8601 timestamp of analysis
   */
  analyzed_at: string;
  /**
   * Number of prompts analyzed
   */
  prompt_count: number;
  [k: string]: unknown;
}
/**
 * Before/after rewrite of weakest prompt
 */
export interface HaikuRewrite1 {
  /**
   * Original user prompt
   */
  original: string;
  /**
   * Rewritten version of the prompt
   */
  improved: string;
  /**
   * Explanation of why the rewrite is better
   */
  why: string;
  [k: string]: unknown;
}
/**
 * Persisted Haiku analysis cache
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "HaikuCache".
 */
export interface HaikuCache {
  analysis?: HaikuAnalysis1;
  /**
   * When the analysis was performed
   */
  analyzed_at: string;
  /**
   * Hash of the prompts that were analyzed
   */
  prompt_hash: string;
  [k: string]: unknown;
}
/**
 * The cached analysis
 */
export interface HaikuAnalysis1 {
  /**
   * Explanation of the user's current tier
   */
  tier_justification: string;
  /**
   * Top improvement patterns identified
   */
  top_improvements: HaikuImprovement[];
  /**
   * Strengths in the user's prompting
   */
  strengths: string[];
  rewrite?: HaikuRewrite1;
  /**
   * Additional insights and findings
   */
  insights?: Insight[];
  /**
   * ISO 8601 timestamp of analysis
   */
  analyzed_at: string;
  /**
   * Number of prompts analyzed
   */
  prompt_count: number;
  [k: string]: unknown;
}
/**
 * Full response from /api/insights endpoint
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "InsightsResponse".
 */
export interface InsightsResponse {
  /**
   * Overall prompt quality score
   */
  score: number;
  /**
   * Current tier (e.g., 'Bronze', 'Silver', 'Gold')
   */
  tier: string;
  /**
   * Breakdown by dimension
   */
  dimensions: InsightDimension[];
  /**
   * Actionable insights and recommendations
   */
  insights: Insight[];
  /**
   * Percentage of context using cache
   */
  cache_pct?: number;
  /**
   * Average number of turns per session
   */
  avg_turns?: number;
  /**
   * Number of sessions with high context usage
   */
  high_ctx_sessions?: number;
  /**
   * Percentage of specific (not generic) prompts
   */
  specific_pct?: number;
  /**
   * Total number of sessions analyzed
   */
  total_sessions: number;
  /**
   * Average prompt length in characters
   */
  avg_prompt_len?: number;
  /**
   * Ratio of output to input tokens
   */
  output_ratio?: number;
  /**
   * Percentage of prompts showing domain ownership
   */
  ownership_pct?: number;
  /**
   * Percentage of conversations using agents
   */
  agent_usage_pct?: number;
  /**
   * Average number of different tools used per session
   */
  avg_tool_diversity?: number;
  /**
   * Goals to reach next tier
   */
  next_tier_goals?: TierGoal[];
  ai_analysis?: HaikuAnalysis2;
  /**
   * Whether AI analysis is currently being generated
   */
  ai_loading?: boolean;
  [k: string]: unknown;
}
/**
 * Optional AI-generated analysis from Haiku
 */
export interface HaikuAnalysis2 {
  /**
   * Explanation of the user's current tier
   */
  tier_justification: string;
  /**
   * Top improvement patterns identified
   */
  top_improvements: HaikuImprovement[];
  /**
   * Strengths in the user's prompting
   */
  strengths: string[];
  rewrite?: HaikuRewrite1;
  /**
   * Additional insights and findings
   */
  insights?: Insight[];
  /**
   * ISO 8601 timestamp of analysis
   */
  analyzed_at: string;
  /**
   * Number of prompts analyzed
   */
  prompt_count: number;
  [k: string]: unknown;
}
/**
 * Top-level aggregated dashboard statistics response
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "Stats".
 */
export interface Stats {
  /**
   * Number of sessions in current filter
   */
  total_sessions: number;
  /**
   * Total number of sessions unfiltered
   */
  total_all_sessions?: number;
  /**
   * Sum of all input tokens
   */
  total_input_tokens: number;
  /**
   * Sum of all output tokens
   */
  total_output_tokens: number;
  /**
   * Sum of all cache read tokens
   */
  total_cache_read_tokens?: number;
  /**
   * Sum of all cache creation tokens
   */
  total_cache_creation_tokens?: number;
  /**
   * Estimated total cost in USD
   */
  total_cost_usd: number;
  /**
   * Average cost per session in USD
   */
  avg_session_cost_usd?: number;
  /**
   * Average total tokens per session
   */
  avg_session_tokens?: number;
  /**
   * Daily breakdown of statistics
   */
  daily: DailyStats[];
  /**
   * Aggregated tool usage counts
   */
  tool_counts: {
    [k: string]: number;
  };
  active_session?: Session1;
  /**
   * List of unique projects in the data
   */
  projects: string[];
  [k: string]: unknown;
}
/**
 * Currently active session if any
 */
export interface Session1 {
  /**
   * Unique session identifier
   */
  id: string;
  /**
   * Full path to the session file
   */
  file_path?: string;
  /**
   * Root directory of the project being worked on
   */
  project_dir: string;
  /**
   * Git branch name active during the session
   */
  git_branch?: string;
  /**
   * Model name used throughout the session
   */
  model: string;
  /**
   * ISO 8601 timestamp when session started
   */
  start_time: string;
  /**
   * ISO 8601 timestamp when session ended
   */
  end_time: string;
  /**
   * Number of user messages in the session
   */
  user_turns: number;
  /**
   * Number of assistant messages in the session
   */
  assist_turns: number;
  total_usage: Usage2;
  /**
   * Map of tool names to invocation counts
   */
  tool_counts?: {
    [k: string]: number;
  };
  /**
   * Map of tool names to up to 5 sample input examples
   */
  tool_samples?: {
    [k: string]: string[];
  };
  /**
   * The very first user prompt in the session
   */
  first_prompt?: string;
  /**
   * Source IDE or editor where the session originated
   */
  source: "claude-code" | "github-copilot" | "opencode" | "windsurf";
  /**
   * Maximum duration of any single turn in milliseconds
   */
  max_turn_duration_ms?: number;
  /**
   * Average duration across all turns in milliseconds
   */
  avg_turn_duration_ms?: number;
  [k: string]: unknown;
}
/**
 * One task item from the todo system
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "TodoItem".
 */
export interface TodoItem {
  /**
   * Task description text
   */
  content: string;
  /**
   * Current status of the todo
   */
  status: "pending" | "in_progress" | "completed";
  /**
   * Session where this todo was created
   */
  session_id?: string;
  [k: string]: unknown;
}
/**
 * System metadata and configuration information
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "SystemInfo".
 */
export interface SystemInfo {
  /**
   * List of enabled plugins
   */
  enabled_plugins?: string[];
  /**
   * List of available MCP servers
   */
  mcp_servers?: string[];
  /**
   * Whether extended thinking is enabled
   */
  always_thinking_enabled?: boolean;
  /**
   * Total number of session files
   */
  total_session_files?: number;
  /**
   * Total number of unique projects
   */
  total_project_dirs?: number;
  /**
   * Number of plans created
   */
  plan_count?: number;
  /**
   * Number of tasks created
   */
  task_count?: number;
  /**
   * Total messages across all sessions
   */
  total_messages_all_time?: number;
  /**
   * Date of first session
   */
  first_session_date?: string;
  /**
   * Model usage statistics
   */
  model_usage?: ModelStats[];
  /**
   * Number of items in paste cache
   */
  paste_cache_count?: number;
  /**
   * Number of items in file history
   */
  file_history_count?: number;
  /**
   * Number of completed todos
   */
  todos_completed?: number;
  /**
   * Number of pending todos
   */
  todos_pending?: number;
  /**
   * Recently created todos
   */
  recent_todos?: TodoItem[];
  [k: string]: unknown;
}
/**
 * Task summary aggregated per project
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "ProjectTaskSummary".
 */
export interface ProjectTaskSummary {
  /**
   * Project directory path
   */
  project_dir: string;
  /**
   * Number of completed tasks
   */
  completed: number;
  /**
   * Number of tasks in progress
   */
  in_progress: number;
  /**
   * Number of pending tasks
   */
  pending: number;
  /**
   * Completion percentage (0-100)
   */
  completion_rate: number;
  /**
   * List of all tasks for this project
   */
  tasks?: TaskItem[];
  [k: string]: unknown;
}
/**
 * Response from /api/tasks endpoint
 *
 * This interface was referenced by `AIUsageDashboardDataModels`'s JSON-Schema
 * via the `definition` "TasksResponse".
 */
export interface TasksResponse {
  /**
   * Task summaries by project
   */
  projects: ProjectTaskSummary[];
  /**
   * Aggregate summary across all projects
   */
  summary: {
    total: number;
    completed: number;
    in_progress: number;
    pending: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
